### ISSUE TITLE
Custom guard not working

### ISSUE THREAD

**Issue by lukas-frey** [savannabits/filament-modules#13]
When I use a custom guard and log into the dashboard, I get this error:
```php
Filament\FilamentManager::getUserAvatarUrl(): Argument #1 ($user) must be of type 
Illuminate\Database\Eloquent\Model|Illuminate\Contracts\Auth\Authenticatable, null given
```

**Comment by coolsam726** [comment]
@LukasFreyCZ kindly post the steps to reproduce or your guard setup to speed up diagnosis on my end. Thanks.

**Comment by coolsam726** [comment]
Closing this as I couldn't re-produce. If the issue is still affecting you please feel free to reopen.
