### ISSUE TITLE
Install Error / Update to Laravel 10

### ISSUE THREAD

**Issue by BennyH2** [savannabits/filament-modules#14]
When trying to install the Filament Modules I get the following error on a fresh install of Laravel 10, Filamentphp, and Filament Sheild. 

Problem 1
    - Root composer.json requires savannabits/filament-modules ^1.0 -> satisfiable by savannabits/filament-modules[v1.0.0, ..., v1.0.4].    
    - savannabits/filament-modules[v1.0.0, ..., v1.0.4] require illuminate/contracts ^9.0 -> found illuminate/contracts[v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.

**Comment by otavio-araujo** [comment]
I got the same here.

Tried to find out a solution through google... but,  without success...

**Comment by yezzdesign** [comment]
Same here, so maybe the admin see this.

**Comment by coolsam726** [comment]
The issue reads right, this is because we haven't supported `Laravel ^10` yet. Not to worry, I am going to do a release in a few minutes that supports Laravel 10. Sorry for the wait.

**Comment by OverboredThekid** [comment]
> The issue reads right, this is because we haven't supported `Laravel ^10` yet. Not to worry, I am going to do a release in a few minutes that supports Laravel 10. Sorry for the wait.

You are an absolute baddie!

**Comment by otavio-araujo** [comment]
@coolsam726 Thank you very much!

**Comment by coolsam726** [comment]
This has been fixed by PR #15
