### ISSUE TITLE
Target class [cache] does not exist.

### ISSUE THREAD

**Issue by tekleberhan** [savannabits/filament-modules#19]
Illuminate
 \ 
Contracts
 \ 
Container
 \ 
BindingResolutionException

This happens when i add filament to module like option 1 and option 2. please help

**Comment by coolsam726** [comment]
Fixed by #27

**Comment by XarchencoMO** [comment]
The error returned in v2.0.1, i created module via command: 
`php artisan module:make TestModule `
and created filament-context via command: 
`php artisan module:make-filament Filament TestModule`
when i try to open some page in project, i get this error 
Target class [cache] does not exist
