### ISSUE TITLE
restrict access to module 

### ISSUE THREAD

**Issue by marco76tv** [savannabits/filament-modules#24]
How to restrict access to module based on a Middleware or Permission or other ?

**Comment by dassudip2001** [comment]
I think  role base permission is the best way to manage

**Comment by coolsam726** [comment]
Hi. This needed quite some work. I had to extend and override most of the functionalities of Filament Shield to support multiple contexts and modules. The work is mostly done, but I need help in beta testing. I have released v2.0.0-beta for this very reason. Kindly test and give feedback. Feel free to reopen this if the issue still persists.

**Comment by coolsam726** [comment]
Hi. This needed quite some work. I had to extend and override most of the functionalities of Filament Shield to support multiple contexts and modules. The work is mostly done, but I need help in beta testing. I have released v2.0.0-beta for this very reason. Kindly test and give feedback. Feel free to reopen this if the issue still persists.

**Comment by dassudip2001** [comment]
I can interested to test? Can you plz explain how to check?
