### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by marco76tv** [savannabits/filament-modules#46]
### What happened?

i don't see the list of modules on primary dashboard

### How to reproduce the bug

go to /admin after login

### Package Version

3

### PHP Version

8.2

### Laravel Version

9

**Comment by coolsam726** [comment]
Fixed by #65 
We will now be using Filament Clusters instead of manually hacking the registration of resources. With the introduction of Panels, we now only need to register the package's plugin in your panel of choice and it will do all the work of loading the modules' resources and pages.
