### ISSUE TITLE
[Bug]: cannot install for filament v3 

### ISSUE THREAD

**Issue by XarchencoMO** [savannabits/filament-modules#48]
### What happened?

 Problem 1
    - coolsam/modules[v1.0.0, ..., v1.3.3, v2.0.0, ..., v2.0.1] require filament/filament ^2.0 -> found filament/filament[v2.5.3, ..., v2.17.53] but it conflicts with your root composer.json require (^v3.0).
    - Root composer.json requires coolsam/modules * -> satisfiable by coolsam/modules[v1.0.0, ..., v1.3.3, v2.0.0, v2.0.1].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require savannabits/filament-modules:*" to figure out if any version is installable, or "composer require savannabits/filament-modules:^2.1" if you know which you need.

### How to reproduce the bug

i created new laravel app (from skeleton), and installed filament v3, then I wanted to install your plugin, but got this error

### Package Version

2.0.1

### PHP Version

8.1

### Laravel Version

^v10.0

### Which operating systems does with happen with?

Linux

**Comment by markpavia** [comment]
@XarchencoMO how did you fix this?
