### ISSUE TITLE
The error returned in v2.0.1, i created module via command:

### ISSUE THREAD

**Issue by XarchencoMO** [savannabits/filament-modules#50]
The error returned in v2.0.1, i created module via command: 
`php artisan module:make TestModule `
and created filament-context via command: 
`php artisan module:make-filament Filament TestModule`
when i try to open some page in project, i get this error 
Target class [cache] does not exist

_Originally posted by @XarchencoMO in https://github.com/savannabits/filament-modules/issues/19#issuecomment-1712570637_

**Comment by coolsam726** [comment]
Fixed By #65 
We will no longer be using the Filament Contexts package, as Filament 3 now supports multiple Panels.
