### ISSUE TITLE
[Bug]: String "Main Panel" not translatable

### ISSUE THREAD

**Issue by Hussam92** [savannabits/filament-modules#51]
### What happened?

Can you please make "Main Panel" translateable? 

```php
__("Main Panel")
```

would be enough

### How to reproduce the bug

"Main Panel" not translateable

### Package Version

2.0.0

### PHP Version

8.2.0

### Laravel Version

10

**Comment by coolsam726** [comment]
Fixed by #75
In v3 this won't be necessary since we will be using clusters instead of Panels, hence the only label that will need translation as at now is the Cluster Navigation Label.
