### ISSUE TITLE
[Bug]: Cannot install with Filament 3

### ISSUE THREAD

**Issue by michael-grunewalder** [savannabits/filament-modules#53]
### What happened?

When I use 'composer require coolsam/modules' as instructed in the 3.x readme, it gives me an error that it is looking form Filament 2.x

### How to reproduce the bug

new Laravel Project with filament 3
composer require coolsam/modules

### Package Version

3.x branch

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

macOS

**Comment by sjardim** [comment]
Had the same problem. Version 3 is not been officially released, so if you change your Laravel project compose.json "minimum-stability" from "stable" to "dev", it will install the package's latest beta version. :)

**Comment by vahidForughi** [comment]
I have the same . any solution ?

**Comment by sjardim** [comment]
> I have the same . any solution ?

Change your Laravel project **compose.json** "minimum-stability" from "stable" to "dev", it will install the package's latest beta version. You can then change it back to "stable".

**Comment by coolsam726** [comment]
Sorry people for the long silence. I am working on a rewrite that will fix most of these issues. Keep an eye out for a stable version 3 of the  package in the next few hours.

**Comment by coolsam726** [comment]
Fixed by #65 
We have re-written the package to address this bug. A stable 3.x version will fix this.
