### ISSUE TITLE
[Bug]: After following the Installation and usage, 404 return as navigate to your module-path/panel-path e.g blog/admin

### ISSUE THREAD

**Issue by luckykenlin** [savannabits/filament-modules#55]
### What happened?

After following the Installation and usage, 

404 return as navigate to your module-path/panel-path e.g blog/admin

If I manually register the BlogPanelProvider in config/app.php    everything works fine.

Should I need to register it?  or something I have missing.

### How to reproduce the bug

Fresh install laravel 10 and filament

Following the Installation and usage on this repo.

visit blog/admin. example:   filament-modules.test/blog/admin

### Package Version

3.0@beta

### PHP Version

8.1

### Laravel Version

10.42

**Comment by coolsam726** [comment]
Fixed by #65 
A rewrite of the package now users nwidart/laravel-modules:^10 and uses a different strategy to load modules. A stable release of 3.x will resolve this.
